### ISSUE TITLE
🛠️ Refactoring: 모임-메인

### ISSUE THREAD

**Issue by slr-09** [KUIT-CoNet/CoNet-iOS#11]
### Descrpiton
모임 > 메인 전체를 리팩토링 합니다. 

### Todo
- [x] #31 
- [x] 모임 정보 수정 화면
- [x] (안진) #52
- [x] (안진) 초대 코드 발급

### Information / ETC
- 긴급도: `Mid` (High/Mid/Low로 적어주세요!)
- 예상 소요 시간: `4d+` (시간은 h, 하루 이상 걸린다면 d!)

**Comment by anjiniii** [comment]
초대 코드 팝업의 초대 코드 입력 적용은 아직 마무리되지 않았지만, 모임-메인에 해당하는 내용은 모두 마무리되어 이슈를 닫습니다!
